CREATE TABLE PERSONAJES(
	IDPERSONAJE int NOT NULL PRIMARY KEY,
	NOMBRE nvarchar(100) NULL,
	IMAGEN nvarchar(500) NULL,
	DESCRIPCION nvarchar(1500) NULL);


INSERT INTO PERSONAJES  VALUES (1,'Koothrappali','koothrappali.png','Conocido como Raj nació en India y trabaja como astrofísico en Caltech. Su mayor logro profesional es el descubrimiento de un nuevo objeto astronómico más allá del cinturón de Kuiper al que llamó Planet Bollywood (en alusión al Hollywood indio), lo que le valió aparecer en la revista People. Frecuentemente se comunica con sus padres por Internet, quienes constantemente le inducen a que tenga relaciones con mujeres, pues sospechan que Raj es homosexual y que su pareja es Howard, situación que la misma serie ironiza; puesto que ambos en ocasiones tienen discusiones propias de un matrimonio en conflicto, han llegado a besarse (por accidente) y Raj se pone celoso cuando Howard da detalles sobre su sexualidad.');
INSERT INTO PERSONAJES  VALUES (2,'Barney Stinson','barney.jpg','Barney Stinson es uno de los cinco personajes principales de How I Met Your Mother. Él está en sus treinta y tantos años, lleva un traje, le gustan las mujeres con problemas con sus padres y está con frecuencia dispuesto a ofrecer su (a veces hipócrita) opinión. A principios Barney es un gran mujeriego, y ha sido descrito como un sociópata de alto funcionamiento, su mejor amigo, Ted Mosby, quiere sentar cabeza. Stinson tiene una gran cantidad de estrategias y reglas diseñadas para cumplir con las mujeres, dormir con ellas y desecharlas. A través de varias temporadas de la serie, cuatro de los personajes principales son parejas, como Ted comenzó a salir con Robin Scherbatsky y el compañero de Ted, Marshall Eriksen se comprometió y se casó con Lily Aldrin. Esto dejó a Stinson como el único personaje soltero, y, según Harris, Stinson fue \"resentido\" que los otros personajes habían emparejado. Más tarde, en la temporada 5, salía con Robin.');
INSERT INTO PERSONAJES  VALUES (3,'Dustin Henderson','dustin.jpg','En la tarde del 6 de noviembre de 1983, Dustin, Lucas, Mike y Will jugaron Dragones y Mazmorras en el sótano de Mike. Mike, actuando como Dungeon Master, convocó a un Demogorgon, que finalmente derrotó al personaje de Will. Mientras buscaban los dados perdidos, la madre de Mike insistió en que era hora de que sus amigos se fueran; poco después de esto, Lucas, Dustin y Will regresaron a casa.');
INSERT INTO PERSONAJES  VALUES (4,'Oliver Atom','oliveratom.jpg','A principios de la serie, Tsubasa, era solo un muchacho obsesionado con el fútbol, un estudiante de escuela primaria que acaba de mudarse a la ciudad de Nankatsu (dentro de la prefectura de Shizuoka) con su madre. Inmediatamente después de su llegada, intenta explorar la nueva ciudad, y llega al campo de fútbol local donde los jugadores de escuela primaria Nankatsu (Niupi o New Team), conducida por Ishizaki (Bruce Harper), se disputan con los jugadores de escuela primaria Shutetsu (San Francis) sobre quién debe usar el campo de fútbol. Impresionado por la calidad del portero, Benji Price (Genzo Wakabayashi) de Shutetsu, Tsubasa decide desafiarlo a un duelo. Este es el principio de la amistad y rivalidad entre ambos.');
INSERT INTO PERSONAJES  VALUES (5,'Benji Price','benji.jpg','Genzo, hijo de una rica y poderosa familia de Japón, vive junto con su entrenador en una mansión en medio de la ciudad, donde día a día práctica para ser el mejor portero del mundo. Es así como se hizo con la fama de un portero invencible ganándose el título de S. G. G. K, Super Great Goal Keeper. (En España y Latinoamérica se le apodó como Benji pantera Price y Benji Price paralotodo)');
INSERT INTO PERSONAJES  VALUES (6,'Once','once.jpg','Once (nacida como Jane Ives) nace en el pueblo de Hawkins, el 22 de agosto de 1971, siendo hija biológica de Teresa Terry Ives y participante en los experimentos del Proyecto MKUltra realizados por la Agencia Central de Inteligencia (CIA). Once parece haber nacido psíquica con notables habilidades telequinéticas y extrasensoriales. Sin embargo, cuando usa estas habilidades en un grado significativo, se debilita temporalmente y le sangra la nariz. Al nacer, Eleven fue separada de su madre por el Dr. Martín Brenner y fue criada en un laboratorio nacional ubicado a las afueras del pueblo, en Indiana, como sujeto de prueba para desarrollar sus habilidades psicoquinéticas. Cuando se coloca en un tanque de privación sensorial, puede usar la visualización remota para acceder a otras dimensiones, principalmente con fines de espionaje internacional. Once, sin saberlo, abre una puerta entre el Laboratorio Nacional de Hawkins y una dimensión alternativa llamada El Otro Lado (Upside Down, en inglés) que permite el paso de criaturas extrañas de un lado a otro.');
INSERT INTO PERSONAJES  VALUES (7,'Sheldon Cooper','sheldon.jpg','Su personalidad es difícil y está fuertemente caracterizada por la egolatría que le hace considerarse intelectualmente superior a todo ser que le rodea, de ese modo subestima a los ingenieros como los Oompa Loompa de la ciencia​ (en referencia a los obreros enanos de Willy Wonka), afirmando que la ingeniería es la hermana menor retrasada de la física y da por supuesto que ganará el Premio Nobel. Pese a su gran inteligencia, tiene serios problemas con tareas sencillas que se niega a reconocer, por ejemplo el ejercicio físico o el conducir un vehículo. Considera a Leonard, Penny y Rajesh sus tres mejores amigos mientras a Howard lo considera solamente un conocido estimado.');
INSERT INTO PERSONAJES  VALUES (8,'Ted Mosby','tedmosby.jpg','Después de terminar la Universidad se mudan a Nueva York con Marshall Eriksen. Ahí se vuelve amigo de Barney Stinson, a quien conocen en el bar MacLarens. Marshall Eriksen decide proponer matrimonio a Lily Aldrin, y ahí es cuando Ted se preocupa sobre el rumbo de su vida amorosa y decide comenzar la búsqueda del amor de su vida, justo comenzando su búsqueda conoce a Robin Scherbatsky, una joven canadiense de la cual se enamora de inmediato y tienen una cita en la cual Ted termina arruinando al decirle que la ama.');
INSERT INTO PERSONAJES  VALUES (9,'El Mandaloriano','mandalorian.png','Cinco años después de los eventos de El Retorno del Jedi y la caída del imperio galáctico, The Mandalorian sigue a Din Djarin, un cazarrecompensas mandaloriano solitario en los confines de la galaxia. 10​ Es contratado por las fuerzas imperiales remanentes para recuperar al niño Grogu, pero en su lugar huye para protegerlo.  Mientras buscan reunir a Grogu con los de su clase, son perseguidos por Moff Gideon, que quiere usar la conexión de Grogu con la Fuerza. Para la tercera temporada, el dúo viajara a Mandalore para que Din Djarin pueda redimirse por la transgresión de quitarse el casco.');
INSERT INTO PERSONAJES  VALUES (10,'Baby Yoda','babyyoda.jpg','Din Grogu (también conocido como Bebé Yoda o Baby Yoda por los seguidores y los medios de comunicación) es un personaje ficticio de la serie de televisión original The Mandalorian, parte de la franquicia Star Wars y emitida en Disney+.');
INSERT INTO PERSONAJES  VALUES (11,'Howard Wolowitz','howard.jpg','Es judío con apariencia anticuada para su época: siempre viste ropa ajustada y psicodélica con un peinado tipo Beatle, además es alérgico a los cacahuetes (maníes). Su mejor amigo es Raj y hasta la sexta temporada aún vivía con su madre, aunque él siempre afirmaba mi madre vive conmigo. Cree que todas las mujeres se sienten atraídas por él, pero la realidad no puede ser más distinta. Es un poco pervertido. Además de lo anterior, es el único de los cuatro amigos que no tiene un doctorado (solo tiene un máster), lo cual desata las burlas de Sheldon.');
INSERT INTO PERSONAJES  VALUES (12,'Daenerys Targaryen','kalesi.jpg','Daenerys Targaryen ​es un personaje ficticio de la serie de novelas de fantasía épica Canción de hielo y fuego, del escritor estadounidense George R. R. Martin. Es uno de los personajes más populares de la serie. El New York Times la considera una de las mejores creaciones del autor.');
INSERT INTO PERSONAJES  VALUES (14,'Tyrion Lannister','tyrion.jpg','Tyrion Lannister (también referido como Gnomo o Mediohombre) es un personaje ficticio de la saga Canción de hielo y fuego de George R. R. Martin y de su correspondiente adaptación televisiva.');
INSERT INTO PERSONAJES  VALUES (15,'Patriota','patriota.jpg','The Boys es una de las series más exitosas de Amazon Prime Video y Homelander (Patriota), el superhéroe más poderoso de esta ficción. Porque el personaje que interpreta el actor neozelandés Antony Starr no se comporta como un héroe. Es un villano, además de un tirano, hedonista, que no conoce de empatía y que es un monstruo por propio derecho. Puede parecer una fusión de Superman (DC Comics) y del Capitán América (Marvel Comics), pero no comparte ninguno de sus valores. Está lleno de traumas y de problemas psicológicos que no hacen más que nublar su juicio, aunque eso no impide que sea el líder de los Siete (The Seven), un grupo igual de fuerte y caótico.');
INSERT INTO PERSONAJES  VALUES (16,'Luz Estelar','luzestelar.jpg','Erin Moriarty como Annie January / Starlight, una joven superheroína que posee la habilidad de emitir rayos de luz a través de sus manos y la miembro más reciente en entrar a los Siete.');
INSERT INTO PERSONAJES  VALUES (17,'Jim Hooper','jimhopper.jpg','En noviembre de 1983, Hopper dirigió la investigación de la desaparición de Will Byers. Habló con los amigos de Will y fue conducido a Mirkwood, donde se encontró con la bicicleta de Will fuera de la carretera, donde empezaba el bosque. Además, fue a casa de Joyce Byers e investigó el cobertizo, donde escuchó ruidos extraños hacia los cuales volteo y una masa viscosa y vibrante fue lo que vieron sus ojos.');
INSERT INTO PERSONAJES  VALUES (18,'Steve Harrington','steve.jpg','Steve es retratado inicialmente como un atleta popular entre las chicas, antagónico y desagradable. Steve había estado saliendo con Nancy Wheeler, pero después de que acosa a Jonathan Byers rompiendo su cámara, Nancy parece volverse cercana a Jonathan. Steve aborda a Jonathan, pero lo vence en una pelea y Steve ve el error de sus acciones e ignora a sus antiguos amigos. Viajando a la casa de los Byers para disculparse, se involucra en la lucha de Nancy y Jonathan contra el Demogorgon, al que derrotan. Al final de la temporada, Nancy le compra a Jonathan una cámara nueva y Steve continúa su relación con ella.');
commit;